# This workflow will build and optionally publish a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ] # Triggers on all tags
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -c Release -r win-x64 --self-contained -p:PublishTrimmed=true -p:PublishAot=true
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Archive build output
      run: |
        mkdir -p output
        Copy-Item -Path "./EXE Proxy/bin/Release/net8.0-windows/win-x64/publish/*" -Destination "./output" -Recurse
    
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -c Release -r win-x64 --self-contained -p:PublishTrimmed=true -p:PublishAot=true
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Archive build output
      run: |
        mkdir -p output
        Copy-Item -Path "./EXE Proxy/bin/Release/net8.0-windows/win-x64/publish/*" -Destination "./output" -Recurse
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        draft: false
        prerelease: false      
        artifacts: "./output/*"
